elasticsearch-master:
  image: 8x8cloud/elasticsearch
  ports: 
    - "9200:9200"
    - "9300:9300"
  container_name: elasticsearch-master

elasticsearch-slave:
  image: 8x8cloud/elasticsearch
  command: elasticsearch --discovery.zen.ping.unicast.hosts=elasticsearch-master
  links:
    - elasticsearch-master

kibana:
  image: 8x8cloud/kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch-master
  environment:
    - "ELASTICSEARCH_HOST=http://elasticsearch-master:9200"
